import React, { useEffect, useState } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  ScrollView, 
  RefreshControl, 
  Alert,
  Modal,
  Share,
  TouchableOpacity,
  Pressable
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { 
  ChevronLeft, ChevronRight, TrendingUp, TrendingDown, 
  Wallet2, AlertTriangle, Grid3x3, Receipt, BarChart3, 
  PiggyBank, AlertCircle, Download, ArrowLeftRight, 
  FileText, X, Calendar 
} from 'lucide-react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { useReportsStore } from '@/stores/reportsStore';
import { useAuthStore } from '@/stores/authStore';
import { useUser } from '@clerk/clerk-expo';
import GradientHeader from '@/components/budgets/GradientHeader';
import ReportPieChart from '@/components/reports/ReportPieChart';
import ReportsSkeleton from '@/components/reports/ReportsSkeleton';
import InteractivePressable from '@/components/common/InteractivePressable';
import MonthHighlight from '@/components/reports/MonthHighlight';
import TransactionItem from '@/components/transactions/TransactionItem';
import { COLORS, SPACING, BORDER_RADIUS, TYPOGRAPHY, SHADOWS, BUDGET } from '@/constants/design';

export default function ReportsScreen(): React.ReactElement {
  const { 
    currentReport,
    selectedMonth,
    isLoading, 
    error, 
    setSelectedMonth,
    fetchMonthlyReport,
    refreshCurrentReport,
    clearError,
    fetchReportComparison,
    comparison
  } = useReportsStore();
  
  const { user } = useUser();
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [showCompareModal, setShowCompareModal] = useState(false);
  const [compareMonth, setCompareMonth] = useState<string>('');

  useEffect(() => {
    if (user) {
      fetchMonthlyReport(selectedMonth, user.id);
    }
  }, [user, selectedMonth]);

  const handleRefresh = async (): Promise<void> => {
    if (!user) return;
    
    setIsRefreshing(true);
    clearError();
    
    try {
      await refreshCurrentReport(user.id);
      if (compareMonth) {
        await fetchReportComparison(selectedMonth, compareMonth, user.id);
      }
    } catch (error) {
      console.error('Error during refresh:', error);
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleGoBack = (): void => {
    router.back();
  };

  const handleMonthChange = (direction: 'prev' | 'next'): void => {
    const currentDate = new Date(selectedMonth + '-01');
    
    if (direction === 'prev') {
      currentDate.setMonth(currentDate.getMonth() - 1);
    } else {
      currentDate.setMonth(currentDate.getMonth() + 1);
    }
    
    const newMonth = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}`;
    setSelectedMonth(newMonth);
    
    // Reset comparison if changing main month
    if (compareMonth) {
      setCompareMonth('');
      // Ideally clear comparison in store too
    }
  };

  const formatMonthYear = (monthString: string): string => {
    const date = new Date(monthString + '-01');
    return date.toLocaleDateString('en-US', { 
      month: 'long', 
      year: 'numeric' 
    });
  };

  const formatMoney = (value: number, withDecimals = false): string =>
    `₵${value.toLocaleString('en-US', {
      minimumFractionDigits: withDecimals ? 2 : 0,
      maximumFractionDigits: withDecimals ? 2 : 0,
    })}`;

  const handleExportReport = async (): Promise<void> => {
    if (!currentReport) return;
    
    try {
      const message = `
Monthly Financial Report - ${formatMonthYear(selectedMonth)}

Summary:
Total Income: ₵${currentReport.totalIncome.toFixed(2)}
Total Expenses: ₵${currentReport.totalExpenses.toFixed(2)}
Net Income: ₵${currentReport.netIncome.toFixed(2)}

Top Spending Categories:
${currentReport.topCategories.map(c => `- ${c.categoryName}: ₵${c.totalAmount.toFixed(2)} (${c.percentage.toFixed(1)}%)`).join('\n')}

Generated by Personal Finance App
      `.trim();

      await Share.share({
        message,
        title: `Financial Report - ${formatMonthYear(selectedMonth)}`
      });
    } catch (error) {
      Alert.alert('Error', 'Failed to export report');
    }
  };

  const handleCompareMonths = (): void => {
    setShowCompareModal(true);
  };

  const executeComparison = async (monthToCompare: string) => {
    if (!user) return;
    
    setCompareMonth(monthToCompare);
    setShowCompareModal(false);
    
    try {
      await fetchReportComparison(selectedMonth, monthToCompare, user.id);
    } catch (error) {
      Alert.alert('Error', 'Failed to generate comparison');
    }
  };

  const combinedLoading = isLoading || isRefreshing;

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView 
        style={styles.mainScrollView}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl 
            refreshing={isRefreshing} 
            onRefresh={handleRefresh}
            tintColor={COLORS.primary}
            colors={[COLORS.primary]}
          />
        }
      >
        {/* Gradient Header Section */}
        <GradientHeader
          title="Financial Reports"
          subtitle="Monthly insights and trends"
          onBackPress={handleGoBack}
          onCalendarPress={() => {}}
          onNotificationPress={() => router.push('/notifications')}
          showCalendar={false}
        />

        {/* Content Card */}
        <View style={styles.contentCard}>
          {/* Error Display */}
          {error && (
            <View style={styles.errorContainer}>
              <AlertCircle size={20} color={COLORS.error} />
              <Text style={styles.errorText}>{error}</Text>
              <InteractivePressable 
                style={styles.errorRetryButton}
                onPress={handleRefresh}
              >
                <Text style={styles.errorRetryText}>Retry</Text>
              </InteractivePressable>
            </View>
          )}

          {/* Month Navigation using new Component */}
          <MonthHighlight 
            selectedMonth={selectedMonth}
            onPrevious={() => handleMonthChange('prev')}
            onNext={() => handleMonthChange('next')}
            onCalendarPress={() => setShowCompareModal(true)} // Can be reused for strict date picking later
          />

          {currentReport && (
            <Animated.View entering={FadeInDown.delay(60).duration(550)} style={styles.overviewWrap}>
              <LinearGradient
                colors={['#033327', COLORS.primary, COLORS.secondary]}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={styles.overviewCard}
              >
                <View style={styles.overviewHeader}>
                  <Text style={styles.overviewTitle}>Report Overview</Text>
                  <Text style={styles.overviewMonth}>{formatMonthYear(selectedMonth)}</Text>
                </View>

                <View style={styles.overviewValueRow}>
                  <Text style={styles.overviewLabel}>Net Income</Text>
                  <Text style={[styles.overviewValue, currentReport.netIncome < 0 && styles.overviewValueNegative]}>
                    {currentReport.netIncome >= 0 ? '+' : '-'}
                    {formatMoney(Math.abs(currentReport.netIncome), true)}
                  </Text>
                </View>

                <View style={styles.overviewStatsRow}>
                  <View style={styles.overviewStatPill}>
                    <Text style={styles.overviewStatLabel}>Transactions</Text>
                    <Text style={styles.overviewStatValue}>{currentReport.transactionCount || 0}</Text>
                  </View>
                  <View style={styles.overviewStatPill}>
                    <Text style={styles.overviewStatLabel}>Savings Rate</Text>
                    <Text style={styles.overviewStatValue}>
                      {currentReport.totalIncome > 0
                        ? `${((currentReport.netIncome / currentReport.totalIncome) * 100).toFixed(1)}%`
                        : '0.0%'}
                    </Text>
                  </View>
                </View>
              </LinearGradient>
            </Animated.View>
          )}
          
          {/* Combined Loading Handler */}
          {combinedLoading ? (
             <ReportsSkeleton />
          ) : (
            <>
              {/* Report Summary Section */}
              <Animated.View entering={FadeInDown.duration(600)} style={styles.summarySection}>
                {currentReport ? (
                  <View>
                    <ReportPieChart 
                      data={currentReport.categoryBreakdown} 
                      totalExpense={currentReport.totalExpenses} 
                    />
                    
                    {/* Modern Gradient Summary Cards */}
                    <View style={styles.cardsRow}>
                      {/* Income Card */}
                      <LinearGradient
                        colors={[COLORS.emeraldGradientStart, COLORS.emeraldGradientEnd]}
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 1 }}
                        style={styles.gradientCard}
                      >
                         <View style={styles.cardHeader}>
                           <TrendingUp size={20} color={COLORS.white} />
                           <Text style={styles.cardLabel}>Income</Text>
                         </View>
                         <Text style={styles.cardValue}>
                            {formatMoney(currentReport.totalIncome)}
                          </Text>
                      </LinearGradient>

                      {/* Expense Card */}
                      <LinearGradient
                        colors={['#EF4444', '#DC2626']} // Red gradient for better contrast/meaning
                        start={{ x: 0, y: 0 }}
                        end={{ x: 1, y: 1 }}
                        style={styles.gradientCard}
                      >
                         <View style={styles.cardHeader}>
                           <TrendingDown size={20} color={COLORS.white} />
                           <Text style={styles.cardLabel}>Expenses</Text>
                         </View>
                         <Text style={styles.cardValue}>
                            {formatMoney(currentReport.totalExpenses)}
                          </Text>
                      </LinearGradient>
                    </View>

                    {/* Net Income Card - Full Width */}
                    <LinearGradient
                       colors={currentReport.netIncome >= 0 
                         ? [COLORS.primary, '#2563EB'] 
                         : ['#EF4444', '#DC2626']}
                       start={{ x: 0, y: 0 }}
                       end={{ x: 1, y: 0 }}
                       style={styles.netIncomeCard}
                    >
                        <View style={styles.netIncomeContent}>
                          <View>
                            <Text style={styles.netIncomeLabel}>Net Income</Text>
                            <Text style={styles.netIncomeValue}>
                               {currentReport.netIncome >= 0 ? '+' : ''}
                               {formatMoney(currentReport.netIncome, true)}
                            </Text>
                          </View>
                          <View style={styles.netIncomeIcon}>
                            <Wallet2 size={24} color={COLORS.white} />
                          </View>
                        </View>
                    </LinearGradient>

                  </View>
                ) : (
                  <View style={styles.summaryCard}>
                    <Text style={styles.summaryCardTitle}>No Data Available</Text>
                    <Text style={styles.summaryCardText}>
                      No financial data available for the selected month
                    </Text>
                  </View>
                )}
              </Animated.View>

              {/* Quick Insights Grid */}
              <Animated.View entering={FadeInDown.delay(100).duration(600)} style={styles.insightsSection}>
                <Text style={styles.sectionTitle}>Quick Insights</Text>
                <View style={styles.insightsGrid}>
                  <InteractivePressable style={styles.insightCard}>
                    <Grid3x3 size={24} color={COLORS.primary} />
                    <Text style={styles.insightCardTitle}>Top Category</Text>
                    <Text style={styles.insightCardValue}>
                      {currentReport?.topCategories?.[0]?.categoryName || '--'}
                    </Text>
                    <Text style={styles.insightSubtext}>
                      {currentReport?.topCategories?.[0]?.percentage 
                        ? `${currentReport.topCategories[0].percentage.toFixed(0)}%` 
                        : '0%'} of expenses
                    </Text>
                  </InteractivePressable>
                  
                  <InteractivePressable style={styles.insightCard}>
                    <PiggyBank size={24} color={COLORS.success} />
                    <Text style={styles.insightCardTitle}>Savings Rate</Text>
                    <Text style={styles.insightCardValue}>
                      {currentReport && currentReport.totalIncome > 0 
                        ? `${((currentReport.netIncome / currentReport.totalIncome) * 100).toFixed(1)}%`
                        : '--'
                      }
                    </Text>
                     <Text style={styles.insightSubtext}>
                      Target: 20%
                    </Text>
                  </InteractivePressable>
                </View>
              </Animated.View>

              {/* Transactions List (Fixed: Now Showing) */}
              {currentReport?.recentTransactions && currentReport.recentTransactions.length > 0 && (
                <View style={styles.transactionsSection}>
                  <View style={styles.sectionHeader}>
                    <Text style={styles.sectionTitle}>Recent Transactions</Text>
                    <TouchableOpacity onPress={() => router.push('/transactions')}>
                       <Text style={styles.seeAllText}>See All</Text>
                    </TouchableOpacity>
                  </View>
                  
                  {currentReport.recentTransactions?.map((transaction, index) => (
                    <TransactionItem
                      key={transaction.id}
                      transaction={transaction}
                      onPress={(id) => router.push(`/transactions/${id}`)}
                      showSeparator={index < (currentReport.recentTransactions?.length || 0) - 1}
                     />
                  ))}
                </View>
              )}

              {/* Action Buttons */}
              <View style={styles.actionsContainer}>
                <InteractivePressable style={styles.primaryActionButton} onPress={handleExportReport}>
                  <Download size={18} color={COLORS.white} />
                  <Text style={styles.primaryActionButtonText}>Export Report</Text>
                </InteractivePressable>
                
                <InteractivePressable style={styles.secondaryActionButton} onPress={handleCompareMonths}>
                  <ArrowLeftRight size={18} color={COLORS.primary} />
                  <Text style={styles.secondaryActionButtonText}>
                    {compareMonth ? `Comparing: ${formatMonthYear(compareMonth)}` : 'Compare Months'}
                  </Text>
                </InteractivePressable>
              </View>

              {/* Empty State */}
              {!currentReport && !error && (
                <View style={styles.emptyState}>
                  <FileText size={64} color="#d1d5db" />
                  <Text style={styles.emptyStateTitle}>No Report Data</Text>
                  <Text style={styles.emptyStateText}>
                    No financial data available for the selected month.
                  </Text>
                </View>
              )}
            </>
          )}

          {/* Bottom spacing for navigation */}
          <View style={styles.bottomSpacing} />
        </View>
      </ScrollView>

      {/* Comparison Month Selection Modal */}
      <Modal
        visible={showCompareModal}
        transparent
        animationType="slide"
        onRequestClose={() => setShowCompareModal(false)}
      >
        <TouchableOpacity 
          style={styles.modalOverlay} 
          activeOpacity={1} 
          onPress={() => setShowCompareModal(false)}
        >
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>Compare with Month</Text>
              <TouchableOpacity onPress={() => setShowCompareModal(false)}>
                <X size={24} color="#666" />
              </TouchableOpacity>
            </View>
            
            <ScrollView style={styles.monthList}>
              {/* Example previous months - in real app, map availableMonths from store */}
              {[1, 2, 3].map(offset => {
                 const d = new Date(selectedMonth + '-01');
                 d.setMonth(d.getMonth() - offset);
                 const mStr = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
                 
                 return (
                  <InteractivePressable 
                    key={mStr}
                    style={styles.monthItem}
                    onPress={() => executeComparison(mStr)}
                  >
                    <Text style={styles.monthText}>{formatMonthYear(mStr)}</Text>
                    <ArrowLeftRight size={20} color={COLORS.primary} />
                  </InteractivePressable>
                 );
              })}
            </ScrollView>
          </View>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BUDGET.gradientColors.start,
  },
  mainScrollView: {
    flex: 1,
  },
  contentCard: {
    backgroundColor: COLORS.backgroundContent,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    marginTop: -20,
    paddingTop: 20,
    flex: 1,
    minHeight: 600,
  },
  errorContainer: {
    backgroundColor: COLORS.backgroundCard,
    marginHorizontal: SPACING.xl,
    marginTop: SPACING.lg,
    marginBottom: SPACING.md,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.lg,
    flexDirection: 'row',
    alignItems: 'center',
    borderLeftWidth: 4,
    borderLeftColor: COLORS.error,
    ...SHADOWS.sm,
  },
  errorText: {
    flex: 1,
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textPrimary,
    marginLeft: SPACING.sm,
    marginRight: SPACING.md,
  },
  errorRetryButton: {
    backgroundColor: COLORS.error,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: BORDER_RADIUS.md,
  },
  errorRetryText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.sizes.sm,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  summarySection: {
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.xxl,
    marginTop: SPACING.sm,
  },
  overviewWrap: {
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.lg,
  },
  overviewCard: {
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg,
    ...SHADOWS.md,
  },
  overviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SPACING.md,
  },
  overviewTitle: {
    color: '#CCFBF1',
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  overviewMonth: {
    color: '#D1FAE5',
    fontSize: TYPOGRAPHY.sizes.xs,
    fontWeight: TYPOGRAPHY.weights.medium,
  },
  overviewValueRow: {
    marginBottom: SPACING.md,
  },
  overviewLabel: {
    color: '#CCFBF1',
    fontSize: TYPOGRAPHY.sizes.sm,
    marginBottom: 2,
  },
  overviewValue: {
    color: COLORS.white,
    fontSize: 32,
    fontWeight: TYPOGRAPHY.weights.bold,
    letterSpacing: -0.4,
  },
  overviewValueNegative: {
    color: '#FECACA',
  },
  overviewStatsRow: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  overviewStatPill: {
    flex: 1,
    borderRadius: BORDER_RADIUS.lg,
    backgroundColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  overviewStatLabel: {
    color: '#D1FAE5',
    fontSize: TYPOGRAPHY.sizes.xs,
    marginBottom: 2,
  },
  overviewStatValue: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: TYPOGRAPHY.weights.semibold,
  },
  cardsRow: {
    flexDirection: 'row',
    gap: SPACING.lg,
    marginBottom: SPACING.lg,
    marginTop: SPACING.lg,
  },
  gradientCard: {
    flex: 1,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.lg,
    paddingVertical: 32,
    ...SHADOWS.md,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.sm,
    marginBottom: SPACING.md,
  },
  cardLabel: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: TYPOGRAPHY.sizes.md,
    fontWeight: '500',
  },
  cardValue: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: '700',
  },
  netIncomeCard: {
    borderRadius: BORDER_RADIUS.xl,
    padding: 32,
    ...SHADOWS.lg,
  },
  netIncomeContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  netIncomeLabel: {
     color: 'rgba(255,255,255,0.9)',
     fontSize: TYPOGRAPHY.sizes.md,
     marginBottom: 8,
  },
  netIncomeValue: {
     color: COLORS.white,
     fontSize: 36,
     fontWeight: '700',
  },
  netIncomeIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  insightsSection: {
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
    paddingHorizontal: SPACING.xl,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
  },
  seeAllText: {
    fontSize: TYPOGRAPHY.sizes.sm,
    color: COLORS.primary,
    fontWeight: '500',
  },
  insightsGrid: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  insightCard: {
    flex: 1,
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.xl,
    padding: SPACING.xl,
    alignItems: 'flex-start',
    minHeight: 140,
    justifyContent: 'center',
    ...SHADOWS.sm,
  },
  insightCardTitle: {
    fontSize: TYPOGRAPHY.sizes.sm,
    color: COLORS.textTertiary,
    marginTop: SPACING.lg,
    marginBottom: 4,
  },
  insightCardValue: {
    fontSize: 22,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginBottom: 4,
  },
  insightSubtext: {
    fontSize: 12,
    color: COLORS.success,
    marginTop: 4,
  },
  transactionsSection: {
    marginBottom: SPACING.xl,
  },
  actionsContainer: {
    paddingHorizontal: SPACING.xl,
    marginBottom: SPACING.xl,
    gap: SPACING.md,
  },
  primaryActionButton: {
    backgroundColor: COLORS.primary,
    borderRadius: BORDER_RADIUS.huge,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    ...SHADOWS.md,
  },
  primaryActionButtonText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.white,
  },
  secondaryActionButton: {
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.huge,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: SPACING.sm,
    borderWidth: 2,
    borderColor: COLORS.primary,
    ...SHADOWS.sm,
  },
  secondaryActionButtonText: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.primary,
  },
  emptyState: {
    alignItems: 'center',
    padding: SPACING.huge,
    marginTop: SPACING.xl,
  },
  emptyStateTitle: {
    fontSize: TYPOGRAPHY.sizes.xl,
    fontWeight: TYPOGRAPHY.weights.bold,
    color: COLORS.textPrimary,
    marginTop: SPACING.lg,
    marginBottom: SPACING.sm,
  },
  emptyStateText: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textTertiary,
    textAlign: 'center',
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: COLORS.backgroundCard,
    borderRadius: BORDER_RADIUS.lg,
    padding: SPACING.xl,
    alignItems: 'center',
    ...SHADOWS.md,
  },
  summaryCardTitle: {
      fontSize: TYPOGRAPHY.sizes.lg,
      fontWeight: '600',
      marginBottom: SPACING.sm,
  },
  summaryCardText: {
      color: COLORS.textTertiary,
      textAlign: 'center',
  },
  bottomSpacing: {
    height: 150,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.backgroundCard,
    borderTopLeftRadius: BORDER_RADIUS.xl,
    borderTopRightRadius: BORDER_RADIUS.xl,
    maxHeight: '60%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: SPACING.xl,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  modalTitle: {
    fontSize: TYPOGRAPHY.sizes.lg,
    fontWeight: TYPOGRAPHY.weights.semibold,
    color: COLORS.textPrimary,
  },
  monthList: {
    maxHeight: 300,
  },
  monthItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: SPACING.xl,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray100,
  },
  monthText: {
    fontSize: TYPOGRAPHY.sizes.md,
    color: COLORS.textPrimary,
  },
});
